version: "3.7"
services:
  web:
    image: favorite-restaurants
    ports:
      - "8080:80"
    environment:
      - apiUrl=http://localhost:4000/restaurants
    networks: 
            - restaurants
networks: 
    restaurants:
        name: restaurants-network
